config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'welcome#index'

  get   'add/income'          => 'add#income',        as: :add_income
  get   'add/expense'         => 'add#expense',       as: :add_expense

  post  'transaction/search'  => 'welcome#search',    as: :tran_search

  post  'add'                 => 'add#add',           as: :add_save

  put   'transaction/:id'     => 'add#update',        as: :edit

  get   'transaction/:id'     => 'add#show',          as: :transaction
  delete 'transaction/:id'    => 'add#delete',        as: :transaction_delete

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user

  validates :source,  length: { in: 1..30 }

  validates :desc,    length: { in: 1..100 }, uniqueness: { scope: :source,
    message: "Same Source and Description can't be repeated" }

  validates :source, :desc, presence: true

  has_many :trans, foreign_key: "transable_id", class_name: "Transaction", as: :transable, dependent: :destroy, :validate => true

end

app/models/expense_category.rb
class ExpenseCategory < Category

end

app/models/expense_transaction.rb
class ExpenseTransaction < Transaction
end

app/models/income_category.rb
class IncomeCategory < Category

end

app/models/income_transaction.rb
class IncomeTransaction < Transaction
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :user
  belongs_to :transable, polymorphic: true, :validate => true
  validates :amount, :date, presence: true
  validates_associated :transable

  def transable_type=(sType)
     super(sType.to_s.classify.constantize.base_class.to_s)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :name,    length: { in: 1..100 }

  has_many :categories
  has_many :transactions
end

app/controllers/add_controller.rb
class AddController < ApplicationController
  def income
    @cat = IncomeCategory.all
    @type = 'IncomeCategory'
    render "transaction/form", date: "Hi"
  end

  def add
    cid = params[:category][:category_id] rescue nil
    source = params[:source] rescue nil
    desc = params[:desc] rescue nil
    type = params[:type] rescue nil
    date = params[:date] rescue nil
    amount = params[:amount] rescue nil
    flash[:cid] = cid
    flash[:source] = source
    flash[:desc] = desc
    flash[:type] = type
    flash[:date] = date
    flash[:amount] = amount
    if cid.nil? || cid==""
      @cat = Category.new({ source: source, desc: desc, type: type })
      @cat.user = current_user
      if !@cat.save
        return redirect_to :back, alert: @cat.errors
      end
    else
      @cat = Category.find(params[:category][:category_id]) rescue nil
      if @cat.nil?
        return redirect_to :back, alert: 'Please select proper category'
      end
    end

    @tran = Transaction.new({ date: date, amount: amount })
    if @cat.type == 'IncomeCategory'
      @tran.type = 'IncomeTransaction'
    else
      @tran.type = 'ExpenseTransaction'
    end
    @tran.transable = @cat

    if @tran.save
      redirect_to '/'
    else
      redirect_to :back, alert: @tran.errors, cat_selected: cid,
                          source: source, desc: desc,
                          date: date, amount: amount
    end

  end

  def expense
    @cat = ExpenseCategory.all
    @type = 'ExpenseCategory'
    render "transaction/form", date: "Hi"
  end

  def show
    @tran = Transaction.find(params[:id])
    flash[:date] = @tran.date.strftime('%Y-%m-%d')
    flash[:amount] = @tran.amount

    @cate = Category.find(@tran.transable_id)
    flash[:cid] = @cate.id
    flash[:source] = @cate.source
    flash[:desc] = @cate.desc

    @type = @cate.type
    @cat = Category.where(type: @type)
    render "transaction/edit"
  end

  def update
    cid = params[:category][:category_id] rescue nil
    source = params[:source] rescue nil
    desc = params[:desc] rescue nil
    type = params[:type] rescue nil
    date = params[:date] rescue nil
    amount = params[:amount] rescue nil
    if cid.nil? || cid==""
      @cat = Category.new({ source: source, desc: desc, type: type })
      @cat.user = current_user
      if !@cat.save
        return redirect_to :back, alert: @cat.errors, data: params
      end
    else
      @cat = Category.find(params[:category][:category_id]) rescue nil
      if @cat.nil?
        return redirect_to :back, alert: 'Please select proper category',
                            cat_selected: cid,
                            source: source, desc: desc,
                            date: date, amount: amount
      end
    end

    @tran = Transaction.find(params[:id])

    if @cat.type == 'IncomeCategory'
      temp_type = 'IncomeTransaction'
    else
      temp_type = 'ExpenseTransaction'
    end

    if @tran.update({ date: date, amount: amount, type: temp_type, transable: @cat })
      redirect_to :back, notice: 'Transaction Updated'
    else
      redirect_to :back, alert: @tran.errors, cat_selected: cid,
                          source: source, desc: desc,
                          date: date, amount: amount
    end
  end

  def delete
    Transaction.find(params[:id]).delete
    redirect_to '/', alert: 'Transaction Deleted'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    if devise_controller?
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @trans = Transaction.all
    flash[:start_date] = @trans.first.date.strftime('%Y-%m-%d')
    flash[:end_date] = @trans.last.date.strftime('%Y-%m-%d')
  end

  def search
    start_date = Date.strptime(params[:start_date],'%Y-%m-%d')
    end_date = Date.strptime(params[:end_date],'%Y-%m-%d')
    if start_date > end_date
      temp = start_date
      start_date = end_date
      end_date = temp
    end
    if ActiveRecord::Base.connection.instance_values["config"][:adapter] == 'sqlite3'
      @trans = Transaction.where(:date => start_date..end_date.tomorrow)
    else
      @trans = Transaction.where(:date => start_date..end_date)
    end
    flash[:start_date] = start_date.strftime('%Y-%m-%d')
    flash[:end_date] = end_date.strftime('%Y-%m-%d')
    render "welcome/index"
  end

end

app/helpers/add_helper.rb
module AddHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_controller_helper.rb
module WelcomeControllerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinanceManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">FinMan</a>
      <div class="collapse navbar-collapse">

        <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li <%= current_page?(add_income_path) ? 'class=active':'' %> > <%= link_to 'Add Income', add_income_path, :class => 'navbar-link' %> </li>
          <li <%= current_page?(add_expense_path) ? 'class=active':'' %> > <%= link_to 'Add Expense', add_expense_path, :class => 'navbar-link' %></li>
        </ul>
        <% end %>
        <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>

            <li <%= current_page?(edit_user_registration_path) ? 'class=active':'' %> ><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
            <li <%= current_page?(destroy_user_session_path) ? 'class=active':'' %> ><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
          <% else %>
            <li <%= current_page?(new_user_registration_path) ? 'class=active':'' %> ><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
            <li <%= current_page?(new_user_session_path) ? 'class=active':'' %> ><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
          <% end %>
        </ul>
      </div>

    </div>
  </nav>


  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-sm-9 col-sm-offset-1">
      <div class="container-fluid">
        <p>
        <% if user_signed_in? %>
            Hi, <strong><%= current_user.name %></strong>.
        <% end %> <br /> Welcome to Finance Manager.
        </p>
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <% if alert.instance_of? String %>
            <p class="alert alert-danger"><%= alert %></p>
          <% else %>
              <h2><%= pluralize(alert.count, "error") %> prohibited this transaction from being saved:</h2>

              <ul>
              <% alert.each do |key, val| %>
                <li><%= key.to_s.capitalize + ": " + val[0].capitalize %></li>
              <% end %>
              </ul>

          <% end %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/transaction/edit.html.erb
<%= form_tag(edit_path(@tran.id), :role => "form", method: :put ) do %>
<div class="form-group">
  <input type="hidden" name="type" value="<%= @type %>">
  <div class="form-group">
    <%= label_tag(:amount, "Amount:") %>
    <%= number_field_tag 'amount', flash[:amount], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag :date, "Date:"  %>
    <div class='input-group date' id='datetimepicker1'>
      <%= date_field_tag 'date', flash[:date], class: "form-control" %>
      <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>
  <% if !@cat.empty? %>
  <div class="form-group">
    <%= label_tag :category, "Category:" %>

    <%= select("category", "category_id", @cat.collect {|p| [ p.source + ' - ' + truncate(p.desc, length: 20), p.id, { data_source: p.source, data_desc: p.desc } ] }, { include_blank: "Add New", selected: flash[:cid] }, :class => "form-control") %>
  </div>
  <% end %>
  <div class="form-group">
    <%= label_tag :source, "Source:" %>
    <%= text_field_tag :source, flash[:source], class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :desc, "Desc:" %>
    <%= text_field_tag :desc, flash[:desc], class: "form-control" %>
  </div>
  <%= submit_tag "Save", :class => "btn btn-default" %>

  <%= link_to 'Delete', transaction_delete_path(@tran.id),method: :delete, data: {confirm: "Are you sure?"}, :class => "pull-right btn btn-danger" %>
</div>
<% end %>

<script>
  <% if !@cat.empty? %>
  var source = $('option:selected').attr('data_source');
  var desc = $('option:selected').attr('data_desc');
  $("#source").val(source);
  $("#desc").val(desc);
  if($('option:selected').val()!="")
  {
     $('#source').attr("readonly", true);
     $('#desc').attr("readonly", true);
  }
  else {
    $('#source').attr("readonly", false);
    $('#desc').attr("readonly", false);
  }
  $("#category_category_id").on('change',function(){
    var source = $('option:selected').attr('data_source');
    var desc = $('option:selected').attr('data_desc');
    $("#source").val(source);
    $("#desc").val(desc);
    if($('option:selected').val()!="")
    {
       $('#source').attr("readonly", true);
       $('#desc').attr("readonly", true);
    }
    else {
      $('#source').attr("readonly", false);
      $('#desc').attr("readonly", false);
    }
  });
  <% end %>
  $(function() {
    $('input[name="date"]').datepicker({
        format: 'dd-mm-yyyy'
    });
  });
</script>

app/views/transaction/form.html.erb
<%= form_tag('/add', :role => "form" ) do %>
<div class="form-group">
  <input type="hidden" name="type" value="<%= @type %>">
  <div class="form-group">
    <%= label_tag(:amount, "Amount:") %>
    <%= number_field_tag 'amount', flash[:amount], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag :date, "Date:"  %>
    <div class='input-group date' id='datetimepicker1'>
      <%= date_field_tag 'date', flash[:date], class: "form-control" %>
      <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>
  <% if !@cat.empty? %>
  <div class="form-group">
    <%= label_tag :category, "Category:" %>

    <%= select("category", "category_id", @cat.collect {|p| [ p.source + ' - ' + truncate(p.desc, length: 20), p.id, { data_source: p.source, data_desc: p.desc } ] }, { include_blank: "Add New", selected: flash[:cid] }, :class => "form-control") %>
  </div>
  <% end %>
  <div class="form-group">
    <%= label_tag :source, "Source:" %>
    <%= text_field_tag :source, flash[:source], class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :desc, "Desc:" %>
    <%= text_field_tag :desc, flash[:desc], class: "form-control" %>
  </div>
  <%= submit_tag "Save", :class => "btn btn-default" %>
</div>
<% end %>

<script>
  <% if !@cat.empty? %>
  var source = $('option:selected').attr('data_source');
  var desc = $('option:selected').attr('data_desc');
  $("#source").val(source);
  $("#desc").val(desc);
  if($('option:selected').val()!="")
  {
     $('#source').attr("readonly", true);
     $('#desc').attr("readonly", true);
  }
  else {
    $('#source').attr("readonly", false);
    $('#desc').attr("readonly", false);
  }
  $("#category_category_id").on('change',function(){
    var source = $('option:selected').attr('data_source');
    var desc = $('option:selected').attr('data_desc');
    $("#source").val(source);
    $("#desc").val(desc);
    if($('option:selected').val()!="")
    {
       $('#source').attr("readonly", true);
       $('#desc').attr("readonly", true);
    }
    else {
      $('#source').attr("readonly", false);
      $('#desc').attr("readonly", false);
    }
  });
  <% end %>
  $(function() {
    $('input[name="date"]').datepicker({
        format: 'dd-mm-yyyy'
    });
  });
</script>

app/views/welcome/index.html.erb
<%= form_tag('/transaction/search', :role => "form" ) do %>
<div class="form-group">

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= label_tag :date, "Start:"  %>
        <div class='input-group date' id='datetimepicker1'>
          <%= date_field_tag 'start_date', flash[:start_date], class: "form-control" %>
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= label_tag :date, "End:"  %>
        <div class='input-group date' id='datetimepicker1'>
          <%= date_field_tag 'end_date', flash[:end_date], class: "form-control" %>
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= label_tag :date, ""  %>
        <div class='input-group'>
          <%= submit_tag "Submit", :class => "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>




</div>
<% end %>

<% if @trans.any?
      trans = @trans.group(:type).order(:type)
  %>
<%= pie_chart trans.sum(:amount), colors: ["red", "green"] %>
<%= line_chart trans.order(:date).group(:date).sum(:amount), colors: ["red", "green"] %>
<table class="table" style="width:150%;">
  <thead>
    <tr>
      <th>No</th>
      <th>Date</th>
      <th>Amount</th>
      <th>Source</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% count = 0 %>
    <% @trans.order('date DESC').each do |tran| %>
    <tr class="<%= tran.type=="IncomeTransaction"? "success":"danger" %>">
      <% count = count + 1 %>
      <td><%= count %></td>
      <td><%= tran.date.strftime('%B %e %Y') rescue nil %></td>
      <td><%= tran.type=="IncomeTransaction"? "":"-" %>₹<%= tran.amount rescue nil %></td>
      <td><%= tran.transable.source rescue nil %></td>
      <td><%= link_to "Edit", transaction_url(id: tran.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<p>No transactions found.</p>
<% end %>